"""Add PollVote table

Revision ID: 2c57fbdbb4dc
Revises: ab12cd34ef56
Create Date: 2026-08-08 20:43:54.308300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c57fbdbb4dc'
down_revision = 'ab12cd34ef56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=True),
    sa.Column('posted_by_admin_id', sa.String(length=20), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['posted_by_admin_id'], ['admin.admin_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notice_timestamp'), ['timestamp'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technologies', sa.String(length=500), nullable=True),
    sa.Column('image_file', sa.String(length=200), nullable=True),
    sa.Column('video_file', sa.String(length=200), nullable=True),
    sa.Column('github_link', sa.String(length=500), nullable=True),
    sa.Column('live_demo_link', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_timestamp'), ['timestamp'], unique=False)

    op.create_table('poll_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['poll_option.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'poll_id', name='_user_poll_uc')
    )
    op.create_table('project_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='_user_project_like_uc')
    )
    op.create_table('skill_endorsement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('endorser_student_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['endorser_student_id'], ['student.student_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['student_skill.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'endorser_student_id', name='_skill_endorser_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_endorsement')
    op.drop_table('project_like')
    op.drop_table('project_comment')
    op.drop_table('poll_vote')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_timestamp'))

    op.drop_table('project')
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notice_timestamp'))

    op.drop_table('notice')
    # ### end Alembic commands ###
