"""Add DepartmentInterest model

Revision ID: 8e65b9398649
Revises: 2c4d5e6f7a81
Create Date: 2026-08-03 15:22:41.955068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e65b9398649'
down_revision = '2c4d5e6f7a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_rate_limit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('key'))
        batch_op.drop_index(batch_op.f('ix_auth_rate_limit_key'))
        batch_op.create_index(batch_op.f('ix_auth_rate_limit_key'), ['key'], unique=True)

    with op.batch_alter_table('phone_recovery_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('student_id'))
        batch_op.drop_index(batch_op.f('ix_phone_recovery_attempt_student_id'))
        batch_op.create_index(batch_op.f('ix_phone_recovery_attempt_student_id'), ['student_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_recovery_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_recovery_attempt_student_id'))
        batch_op.create_index(batch_op.f('ix_phone_recovery_attempt_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('student_id'), ['student_id'], unique=True)

    with op.batch_alter_table('auth_rate_limit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_rate_limit_key'))
        batch_op.create_index(batch_op.f('ix_auth_rate_limit_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('key'), ['key'], unique=True)

    # ### end Alembic commands ###
