"""Added Study Groups

Revision ID: 9051c422d768
Revises: 92e0142508d3
Create Date: 2026-03-13 10:06:04.553310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9051c422d768'
down_revision = '92e0142508d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('meet_time', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('creator_name', sa.String(length=100), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_group_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['study_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_group_member')
    op.drop_table('study_group')
    # ### end Alembic commands ###
