"""Add user_id to Event

Revision ID: 92e0142508d3
Revises: 
Create Date: 2026-03-13 05:22:38.430805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92e0142508d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('task', sa.String(length=200), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.String(length=20), nullable=False),
    sa.Column('followed_id', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['student.student_id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='_follower_followed_uc')
    ) # The drop_table commands below were removed as they were likely an auto-generation error and could cause data loss.
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # The create_table commands below were removed as they correspond to the
    # drop_table commands removed from the upgrade function.
    op.drop_table('follower')
    op.drop_table('todo')
    # ### end Alembic commands ###
