"""Add image_file to JobPost model

Revision ID: f03915c0a136
Revises: d1a2c3d4e5f6
Create Date: 2026-05-15 12:47:24.256610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f03915c0a136'
down_revision = 'd1a2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_chat_log')
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_timestamp'))

    op.drop_table('assignment')
    op.drop_table('memory')
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    op.create_table('memory',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('image_file', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('assignment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('given_date', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('deadline', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('posted_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('department', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('section', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_timestamp'), ['timestamp'], unique=False)

    op.create_table('ai_chat_log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('response', mysql.TEXT(), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
